# -*-coding:Latin-1 -*

#USER CONFIGURATION#
USER_CODE = # INSERT PIN CODE HERE
PASSWORD = # INSERT PASSWORD HERE
IP_ADDR = # INSERT IP ADDRESS HERE
TCP_PORT = # INSERT PORT HERE (DEFAULT 10000)

STATUS_INTERVAL	= 1
LOGIN_MAX_RETRY	= 20
LOGIN_WAIT_TIME_START = 5
LOGIN_WAIT_TIME_MULT = 3

READY_WAIT_TIME	= 1

SLEEP_TIME = 8
STATE_CODES = {"1": "Desarme", "2": "Arme", "5": "Partiel", "7": "Delais evacuation"};
DET_OPEN_CODES = (1,6)
DET_MEMORY_CODES = (5,6)
