# -*-coding:Latin-1 -*

#USER CONFIGURATION#
USER_CODE = 1234556
PASSWORD = "password"
IP_ADDR = "192.168.1.1"
TCP_PORT = "10000"

WEBSERVER_PORT = 12345
WEBSERVER_HOST = ''

VERBOSE_LEVEL = 2

STATUS_INTERVAL	= 1
LOGIN_MAX_RETRY	= 1
LOGIN_WAIT_TIME_START = 5
LOGIN_WAIT_TIME_MULT = 3
KEEP_ALIVE_ALLOWED_ERRORS = 30

READY_WAIT_TIME	= 1

SLEEP_TIME = 8
STATE_CODES = {"1": "Desarme", "2": "Arme", "5": "Partiel", "7": "Delais evacuation"};
DET_OPEN_CODES = (1,6)
DET_MEMORY_CODES = (5,6)

PARSER_SES_IDENTIFIER		= "loginaff"
PARSER_ZONES_IDENTIFIER		= "tbl_zone"
PARSER_AREAS_IDENTIFIER		= "tbl_areanam"
PARSER_STATES_IDENTIFIER	= "tbl_useraccess"
PARSER_STATUS_IDENTIFIER 	= "tbl_statuszone"
PARSER_EXCLUDED_AREAS 		= (u"Non Assigné".encode("utf-8"))
